### ISSUE TITLE
Issue with lines count

### ISSUE THREAD

**Issue by ghost** [Badranh/Syntax-View-Android#3]
Issue with line counter

![](https://i.imgur.com/IzBty5S.png)

**Comment by Badranh** [comment]
@MohamedElidrissi  thanks for the notice 👍 , will get it fixed soon.
the problem is with the new font it has a smaller size than the old one.

**Comment by Badranh** [comment]
Fixed💃

**Comment by Badranh** [comment]
![screenshot_1530035273](https://user-images.githubusercontent.com/26762008/41930077-aae1b1f4-7982-11e8-889c-76ed8046161c.png)

Tested On Note 3 and emulator ( it works fine!) @MohamedElidrissi  please give it a try at your phone , if the issue still exists please reopen it and comment your phone type

**Comment by ghost** [comment]
The issue persists. I am currently working on an alternative way to display the line count using a custom View instead of a TextView.



![](https://i.imgur.com/5LGpym3.png)

_Sent from my Galaxy J7 Prime using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Badranh** [comment]
@MohamedElidrissi  maybe we can implement like https://github.com/hanks-zyh/LineHeightEditText in our project and use a recycler view to show numbers ,  so we can limit the height of line and then we can create recyclerview of items with the same height of lines what do you think about this solution?

**Comment by Badranh** [comment]
@MohamedElidrissi  I will Try Setting the TextView TypeFace Font to the same Typeface font of code text maybe this will work .  (if this work textview will be better than any other custom view that contains adapter for performance)
        
code = rows.setTypeface(tf);  
put this in initialize method and try the app again
and try adjusting the text size in textview from 18sp to 20sp

I just pushed a fix let us try it! 👍

**Comment by Badranh** [comment]
![screenshot_1530045158](https://user-images.githubusercontent.com/26762008/41937560-4c22c61e-7999-11e8-81b1-e7122c29df53.png)

**Comment by ghost** [comment]
Its fine now. So the setFont method should apply the font to the lines textview and editor.

**Comment by Badranh** [comment]
Yes , it this is the correct final fix  i will try to push the fix tomorrow  ! thanks 👍 for your contribution 💛
